name:        type-integers
version:     0.1.0.0
github:      "serokell/type-integers"
license:     BSD3
author:     "Author name here"
maintainer: "example@example.com"
copyright:  "2020 Author name here"

synopsis:   Type-level integers and proofs of their properties.
category:   Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/serokell/type-integers#readme>.

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Werror=incomplete-patterns
  # TODO: Remove these if able
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-export-lists
  - -Wno-missing-deriving-strategies
  - -Wno-unused-matches
  - -Wno-unused-type-patterns
  - -Wno-unsafe
  - -Wno-prepositive-qualified-module

library:
  source-dirs: src
  dependencies:
    - equational-reasoning
    - singletons
    - type-natural

executables:
  myproject:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - type-natural
      - equational-reasoning
      - singletons
